// @ts-nocheck
import React, { createContext, useContext, useState } from 'react';

/**
 * LanguageContext — Provides multilingual translation support
 * for all CropWise Dashboard components.
 */

const translations = {
  English: {
    // Navbar
    home: 'Home',
    features: 'Features',
    weather: 'Weather',
    // Hero
    badgeText: 'Smart Agriculture Platform',
    heroHeading1: 'Empowering Farmers with',
    heroHeading2: 'Smart Agriculture',
    heroSubheading: '"From Soil to Success — Smarter Farming Starts Here"',
    exploreFeatures: 'Explore Features',
    // Features
    whatWeOffer: 'What We Offer',
    powerfulFeatures: 'Powerful',
    forModernFarming: 'for Modern Farming',
    pmKisanTitle: 'PM-Kisan Navigator',
    pmKisanDesc: 'Check eligibility, status, and scheme benefits instantly.',
    cropDoctorTitle: 'Crop Doctor (AI)',
    cropDoctorDesc: 'Upload crop image and detect disease using AI analysis.',
    smartMandiTitle: 'Smart Mandi',
    smartMandiDesc: 'Get real-time crop prices and market insights near you.',
    farmingPlannerTitle: 'Farming Planner',
    farmingPlannerDesc: 'Plan crops based on season, soil type, and weather data.',
    learnMore: 'Learn more →',
    // Weather
    stayInformed: 'Stay Informed',
    live: 'Live',
    weatherInsights: 'Insights',
    yourLocation: 'Your Location',
    locationName: 'New Delhi, India',
    temperature: 'Temperature',
    humidity: 'Humidity',
    rainProbability: 'Rain Probability',
    windSpeed: 'Wind Speed',
    feelsLike: 'Feels like 31°C',
    moderate: 'Moderate',
    lightShowers: 'Light showers expected',
    nwDirection: 'NW direction',
    // Footer
    madeWith: 'Made with',
    forFeeders: 'for the feeders of the nation',
    about: 'About',
    contact: 'Contact',
    privacy: 'Privacy',
  },
  Hindi: {
    home: 'होम',
    features: 'सुविधाएँ',
    weather: 'मौसम',
    badgeText: 'स्मार्ट कृषि प्लेटफ़ॉर्म',
    heroHeading1: 'किसानों को सशक्त बनाना',
    heroHeading2: 'स्मार्ट कृषि',
    heroSubheading: '"मिट्टी से सफलता तक — स्मार्ट खेती यहाँ से शुरू"',
    exploreFeatures: 'सुविधाएँ देखें',
    whatWeOffer: 'हम क्या प्रदान करते हैं',
    powerfulFeatures: 'शक्तिशाली',
    forModernFarming: 'आधुनिक खेती के लिए',
    pmKisanTitle: 'पीएम-किसान नेविगेटर',
    pmKisanDesc: 'पात्रता, स्थिति और योजना लाभ तुरंत जाँचें।',
    cropDoctorTitle: 'क्रॉप डॉक्टर (AI)',
    cropDoctorDesc: 'फसल की छवि अपलोड करें और AI से रोग पहचानें।',
    smartMandiTitle: 'स्मार्ट मंडी',
    smartMandiDesc: 'अपने पास की मंडी में फसल की कीमतें जानें।',
    farmingPlannerTitle: 'खेती योजनाकार',
    farmingPlannerDesc: 'मौसम, मिट्टी और जलवायु के आधार पर फसल की योजना बनाएँ।',
    learnMore: 'और जानें →',
    stayInformed: 'जानकारी रखें',
    live: 'लाइव',
    weatherInsights: 'जानकारी',
    yourLocation: 'आपका स्थान',
    locationName: 'नई दिल्ली, भारत',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    rainProbability: 'बारिश की संभावना',
    windSpeed: 'हवा की गति',
    feelsLike: 'महसूस होता है 31°C',
    moderate: 'मध्यम',
    lightShowers: 'हल्की बारिश अपेक्षित',
    nwDirection: 'उत्तर-पश्चिम दिशा',
    madeWith: 'बनाया गया',
    forFeeders: 'राष्ट्र के अन्नदाताओं के लिए',
    about: 'हमारे बारे में',
    contact: 'संपर्क',
    privacy: 'गोपनीयता',
  },
  Tamil: {
    home: 'முகப்பு',
    features: 'அம்சங்கள்',
    weather: 'வானிலை',
    badgeText: 'ஸ்மார்ட் வேளாண் தளம்',
    heroHeading1: 'விவசாயிகளை வலுப்படுத்துதல்',
    heroHeading2: 'ஸ்மார்ட் வேளாண்மை',
    heroSubheading: '"மண்ணிலிருந்து வெற்றி வரை — ஸ்மார்ட் விவசாயம் இங்கே தொடங்குகிறது"',
    exploreFeatures: 'அம்சங்களைக் காண',
    whatWeOffer: 'நாங்கள் வழங்குவது',
    powerfulFeatures: 'சக்திவாய்ந்த',
    forModernFarming: 'நவீன விவசாயத்திற்கு',
    pmKisanTitle: 'பிஎம்-கிசான் வழிகாட்டி',
    pmKisanDesc: 'தகுதி, நிலை மற்றும் திட்ட நன்மைகளை உடனடியாகச் சரிபார்க்கவும்.',
    cropDoctorTitle: 'பயிர் மருத்துவர் (AI)',
    cropDoctorDesc: 'பயிர் படத்தைப் பதிவேற்றி AI மூலம் நோயைக் கண்டறியுங்கள்.',
    smartMandiTitle: 'ஸ்மார்ட் மண்டி',
    smartMandiDesc: 'உங்களுக்கு அருகிலுள்ள பயிர் விலைகளைப் பெறுங்கள்.',
    farmingPlannerTitle: 'விவசாய திட்டமிடல்',
    farmingPlannerDesc: 'பருவம், மண் வகை மற்றும் வானிலை தரவு அடிப்படையில் பயிர்களைத் திட்டமிடுங்கள்.',
    learnMore: 'மேலும் அறிக →',
    stayInformed: 'தகவல் அறிக',
    live: 'நேரலை',
    weatherInsights: 'நுண்ணறிவு',
    yourLocation: 'உங்கள் இடம்',
    locationName: 'புது தில்லி, இந்தியா',
    temperature: 'வெப்பநிலை',
    humidity: 'ஈரப்பதம்',
    rainProbability: 'மழை வாய்ப்பு',
    windSpeed: 'காற்றின் வேகம்',
    feelsLike: '31°C போல் உணர்கிறது',
    moderate: 'மிதமான',
    lightShowers: 'இலேசான மழை எதிர்பார்க்கப்படுகிறது',
    nwDirection: 'வடமேற்கு திசை',
    madeWith: 'உருவாக்கப்பட்டது',
    forFeeders: 'நாட்டின் உணவளிப்பவர்களுக்காக',
    about: 'எங்களை பற்றி',
    contact: 'தொடர்பு',
    privacy: 'தனியுரிமை',
  },
  Telugu: {
    home: 'హోమ్',
    features: 'ఫీచర్లు',
    weather: 'వాతావరణం',
    badgeText: 'స్మార్ట్ వ్యవసాయ ప్లాట్‌ఫామ్',
    heroHeading1: 'రైతులను శక్తివంతం చేయడం',
    heroHeading2: 'స్మార్ట్ వ్యవసాయం',
    heroSubheading: '"నేల నుండి విజయం వరకు — స్మార్ట్ వ్యవసాయం ఇక్కడ ప్రారంభం"',
    exploreFeatures: 'ఫీచర్లు చూడండి',
    whatWeOffer: 'మేము అందించేవి',
    powerfulFeatures: 'శక్తివంతమైన',
    forModernFarming: 'ఆధునిక వ్యవసాయం కోసం',
    pmKisanTitle: 'పీఎం-కిసాన్ నావిగేటర్',
    pmKisanDesc: 'అర్హత, స్థితి మరియు పథకం ప్రయోజనాలను తక్షణమే తనిఖీ చేయండి.',
    cropDoctorTitle: 'క్రాప్ డాక్టర్ (AI)',
    cropDoctorDesc: 'పంట చిత్రాన్ని అప్‌లోడ్ చేసి AI ద్వారా వ్యాధిని గుర్తించండి.',
    smartMandiTitle: 'స్మార్ట్ మండి',
    smartMandiDesc: 'మీ సమీపంలోని పంట ధరలు పొందండి.',
    farmingPlannerTitle: 'వ్యవసాయ ప్లానర్',
    farmingPlannerDesc: 'సీజన్, నేల రకం మరియు వాతావరణ డేటా ఆధారంగా పంటలను ప్లాన్ చేయండి.',
    learnMore: 'మరింత తెలుసుకోండి →',
    stayInformed: 'సమాచారంతో ఉండండి',
    live: 'లైవ్',
    weatherInsights: 'అంతర్దృష్టి',
    yourLocation: 'మీ స్థానం',
    locationName: 'న్యూ ఢిల్లీ, భారతదేశం',
    temperature: 'ఉష్ణోగ్రత',
    humidity: 'తేమ',
    rainProbability: 'వర్షం సంభావ్యత',
    windSpeed: 'గాలి వేగం',
    feelsLike: '31°C లా అనిపిస్తుంది',
    moderate: 'మోస్తరు',
    lightShowers: 'తేలికపాటి వర్షాలు ఆశించబడుతున్నాయి',
    nwDirection: 'వాయువ్య దిశ',
    madeWith: 'తయారు చేయబడింది',
    forFeeders: 'దేశానికి ఆహారం అందించేవారి కోసం',
    about: 'మా గురించి',
    contact: 'సంప్రదించండి',
    privacy: 'గోప్యత',
  },
  Bengali: {
    home: 'হোম',
    features: 'বৈশিষ্ট্য',
    weather: 'আবহাওয়া',
    badgeText: 'স্মার্ট কৃষি প্ল্যাটফর্ম',
    heroHeading1: 'কৃষকদের শক্তিশালী করা',
    heroHeading2: 'স্মার্ট কৃষি',
    heroSubheading: '"মাটি থেকে সাফল্য — স্মার্ট চাষ এখানে শুরু"',
    exploreFeatures: 'বৈশিষ্ট্য দেখুন',
    whatWeOffer: 'আমরা যা অফার করি',
    powerfulFeatures: 'শক্তিশালী',
    forModernFarming: 'আধুনিক চাষের জন্য',
    pmKisanTitle: 'পিএম-কিসান নেভিগেটর',
    pmKisanDesc: 'যোগ্যতা, স্থিতি এবং প্রকল্পের সুবিধা তাৎক্ষণিকভাবে পরীক্ষা করুন।',
    cropDoctorTitle: 'ক্রপ ডক্টর (AI)',
    cropDoctorDesc: 'ফসলের ছবি আপলোড করুন এবং AI দিয়ে রোগ শনাক্ত করুন।',
    smartMandiTitle: 'স্মার্ট মান্ডি',
    smartMandiDesc: 'আপনার কাছের ফসলের দাম জানুন।',
    farmingPlannerTitle: 'কৃষি পরিকল্পনাকারী',
    farmingPlannerDesc: 'ঋতু, মাটির ধরন এবং আবহাওয়ার তথ্যের ভিত্তিতে ফসলের পরিকল্পনা করুন।',
    learnMore: 'আরও জানুন →',
    stayInformed: 'জানকারি রাখুন',
    live: 'লাইভ',
    weatherInsights: 'অন্তর্দৃষ্টি',
    yourLocation: 'আপনার অবস্থান',
    locationName: 'নতুন দিল্লি, ভারত',
    temperature: 'তাপমাত্রা',
    humidity: 'আর্দ্রতা',
    rainProbability: 'বৃষ্টির সম্ভাবনা',
    windSpeed: 'বায়ুর গতি',
    feelsLike: '31°C অনুভব হচ্ছে',
    moderate: 'মাঝারি',
    lightShowers: 'হালকা বৃষ্টি প্রত্যাশিত',
    nwDirection: 'উত্তর-পশ্চিম দিক',
    madeWith: 'তৈরি করা হয়েছে',
    forFeeders: 'দেশের অন্নদাতাদের জন্য',
    about: 'আমাদের সম্পর্কে',
    contact: 'যোগাযোগ',
    privacy: 'গোপনীয়তা',
  },
  Marathi: {
    home: 'मुख्यपृष्ठ',
    features: 'वैशिष्ट्ये',
    weather: 'हवामान',
    badgeText: 'स्मार्ट कृषी प्लॅटफॉर्म',
    heroHeading1: 'शेतकऱ्यांना सक्षम करणे',
    heroHeading2: 'स्मार्ट कृषी',
    heroSubheading: '"मातीपासून यशापर्यंत — स्मार्ट शेती इथे सुरू होते"',
    exploreFeatures: 'वैशिष्ट्ये पहा',
    whatWeOffer: 'आम्ही काय देतो',
    powerfulFeatures: 'शक्तिशाली',
    forModernFarming: 'आधुनिक शेतीसाठी',
    pmKisanTitle: 'पीएम-किसान नेव्हिगेटर',
    pmKisanDesc: 'पात्रता, स्थिती आणि योजना लाभ तत्काळ तपासा.',
    cropDoctorTitle: 'क्रॉप डॉक्टर (AI)',
    cropDoctorDesc: 'पिकाची प्रतिमा अपलोड करा आणि AI द्वारे रोग ओळखा.',
    smartMandiTitle: 'स्मार्ट मंडी',
    smartMandiDesc: 'तुमच्या जवळील पिकांचे भाव जाणून घ्या.',
    farmingPlannerTitle: 'शेती नियोजक',
    farmingPlannerDesc: 'हंगाम, मातीचा प्रकार आणि हवामान डेटाच्या आधारे पिकाचे नियोजन करा.',
    learnMore: 'अधिक जाणून घ्या →',
    stayInformed: 'माहिती ठेवा',
    live: 'लाइव्ह',
    weatherInsights: 'अंतर्दृष्टी',
    yourLocation: 'तुमचे स्थान',
    locationName: 'नवी दिल्ली, भारत',
    temperature: 'तापमान',
    humidity: 'आर्द्रता',
    rainProbability: 'पावसाची शक्यता',
    windSpeed: 'वाऱ्याचा वेग',
    feelsLike: '31°C सारखे वाटते',
    moderate: 'मध्यम',
    lightShowers: 'हलक्या पावसाची अपेक्षा',
    nwDirection: 'वायव्य दिशा',
    madeWith: 'बनवले गेले',
    forFeeders: 'राष्ट्राच्या अन्नदात्यांसाठी',
    about: 'आमच्याबद्दल',
    contact: 'संपर्क',
    privacy: 'गोपनीयता',
  },
  Punjabi: {
    home: 'ਹੋਮ',
    features: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ',
    weather: 'ਮੌਸਮ',
    badgeText: 'ਸਮਾਰਟ ਖੇਤੀ ਪਲੇਟਫਾਰਮ',
    heroHeading1: 'ਕਿਸਾਨਾਂ ਨੂੰ ਸਸ਼ਕਤ ਬਣਾਉਣਾ',
    heroHeading2: 'ਸਮਾਰਟ ਖੇਤੀ',
    heroSubheading: '"ਮਿੱਟੀ ਤੋਂ ਸਫਲਤਾ ਤੱਕ — ਸਮਾਰਟ ਖੇਤੀ ਇੱਥੇ ਸ਼ੁਰੂ ਹੁੰਦੀ ਹੈ"',
    exploreFeatures: 'ਵਿਸ਼ੇਸ਼ਤਾਵਾਂ ਦੇਖੋ',
    whatWeOffer: 'ਅਸੀਂ ਕੀ ਪੇਸ਼ ਕਰਦੇ ਹਾਂ',
    powerfulFeatures: 'ਸ਼ਕਤੀਸ਼ਾਲੀ',
    forModernFarming: 'ਆਧੁਨਿਕ ਖੇਤੀ ਲਈ',
    pmKisanTitle: 'ਪੀਐਮ-ਕਿਸਾਨ ਨੈਵੀਗੇਟਰ',
    pmKisanDesc: 'ਯੋਗਤਾ, ਸਥਿਤੀ ਅਤੇ ਯੋਜਨਾ ਲਾਭ ਤੁਰੰਤ ਚੈੱਕ ਕਰੋ।',
    cropDoctorTitle: 'ਕ੍ਰੌਪ ਡਾਕਟਰ (AI)',
    cropDoctorDesc: 'ਫ਼ਸਲ ਦੀ ਤਸਵੀਰ ਅੱਪਲੋਡ ਕਰੋ ਅਤੇ AI ਨਾਲ ਬਿਮਾਰੀ ਪਛਾਣੋ।',
    smartMandiTitle: 'ਸਮਾਰਟ ਮੰਡੀ',
    smartMandiDesc: 'ਤੁਹਾਡੇ ਨਜ਼ਦੀਕ ਫ਼ਸਲ ਦੀਆਂ ਕੀਮਤਾਂ ਪ੍ਰਾਪਤ ਕਰੋ।',
    farmingPlannerTitle: 'ਖੇਤੀ ਯੋਜਨਾਕਾਰ',
    farmingPlannerDesc: 'ਮੌਸਮ, ਮਿੱਟੀ ਦੀ ਕਿਸਮ ਅਤੇ ਮੌਸਮ ਡੇਟਾ ਦੇ ਆਧਾਰ ਤੇ ਫ਼ਸਲ ਦੀ ਯੋਜਨਾ ਬਣਾਓ।',
    learnMore: 'ਹੋਰ ਜਾਣੋ →',
    stayInformed: 'ਜਾਣਕਾਰੀ ਰੱਖੋ',
    live: 'ਲਾਈਵ',
    weatherInsights: 'ਜਾਣਕਾਰੀ',
    yourLocation: 'ਤੁਹਾਡਾ ਸਥਾਨ',
    locationName: 'ਨਵੀਂ ਦਿੱਲੀ, ਭਾਰਤ',
    temperature: 'ਤਾਪਮਾਨ',
    humidity: 'ਨਮੀ',
    rainProbability: 'ਬਾਰਿਸ਼ ਦੀ ਸੰਭਾਵਨਾ',
    windSpeed: 'ਹਵਾ ਦੀ ਗਤੀ',
    feelsLike: '31°C ਜਿਹਾ ਮਹਿਸੂਸ ਹੁੰਦਾ',
    moderate: 'ਮੱਧਮ',
    lightShowers: 'ਹਲਕੀ ਬਾਰਿਸ਼ ਦੀ ਉਮੀਦ',
    nwDirection: 'ਉੱਤਰ-ਪੱਛਮ ਦਿਸ਼ਾ',
    madeWith: 'ਬਣਾਇਆ ਗਿਆ',
    forFeeders: 'ਦੇਸ਼ ਦੇ ਅੰਨਦਾਤਿਆਂ ਲਈ',
    about: 'ਸਾਡੇ ਬਾਰੇ',
    contact: 'ਸੰਪਰਕ',
    privacy: 'ਗੋਪਨੀਯਤਾ',
  },
};

const LanguageContext = createContext({
  language: 'English',
  setLanguage: (/** @type {string} */ _lang) => {},
  t: (/** @type {string} */ _key) => '',
});

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('English');

  /** @param {string} key */
  const t = (key) => {
    const langStrings = translations[language] || translations['English'];
    return langStrings[key] || translations['English'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}

export default LanguageContext;
